### ISSUE TITLE
Should we rename the standard EPICS directory?

### ISSUE THREAD

**Issue by ghost** [lnls-fac/scripts#1]
We could remove the detailed version number and keep only 3.14.12 or 3.14.

**Comment by xresende** [comment]
ok.

**Comment by xresende** [comment]
maybe we should use a symbolic link (_/usr/local/epics/base_) as the default path to the library...

**Comment by ghost** [comment]
That is indeed a good idea. We could create a link to /usr/local/epics/R3.14.12.4 named /usr/local/epics/R3.14 (see http://www.aps.anl.gov/epics/base/R3-14/index.php and http://www.aps.anl.gov/epics/base/R3-15/index.php), so we could have parallel versions installed and update each version separately with patches and new releases.

**Comment by ghost** [comment]
Changed bashrc and created symbolic link.
