### ISSUE TITLE
VA continually restarting in sirius-va

### ISSUE THREAD

**Issue by ghost** [lnls-fac/scripts#7]
When sirius-va is run with argument start, the VA keeps restarting.

**Comment by ghost** [comment]
We can live with it; just start VA manually and use sirius-va to start viocs.

**Comment by xresende** [comment]
![enhanced-26520-1394667762-7](https://cloud.githubusercontent.com/assets/5631815/9421850/abb42ed6-4852-11e5-95c4-39aabae6c90d.jpg)
we'll do! we'll do...
